### ISSUE TITLE
Socket is not invoking if app is closed

### ISSUE THREAD

**Issue by PrabhansuTiw** [codecaplet/FlutterTutorials#1]
I have a system where I am receiving a chat request. It is working perfectly when app is running or in background but when app is closed then I am not able to receive chat request. Please suggest me what can I do for this.

**Comment by codecaplet** [comment]
Hey, sorry I am late to the conversation. Not sure if you are still looking for solution.
But, for this scenario, I am using Firebase Messaging in my app. What I do is:

1. In the flutter app, I register a Firebase messaging service to handle firebase messages. The service creates local notifications.
2. I also push the user's firebase messaging registration token against the user on the server. This I do every time the user opens the app as the older token may have expired.
3. On the server, I maintain a concurrent list of users connected to the websocket. This is accomplished by emitting the the user's id/token from the app as soon as it connects to the websocket.
4. When a new message arrives, along with broadcasting the message from the websocket, I multicast messages to remaining users in the chatroom through firebase.

**Comment by PrabhansuTiw** [comment]
My issue has been resolved now. Thanks for helping me
